### ISSUE TITLE
When Creating a new competition , and importing data, how do you know which competition is in focus?

### ISSUE THREAD

**Issue by gregw94542** [usspeedskating/tempus-public#16]
**Is your feature request related to a problem? Please describe.**
Maybe, could be user error

**Describe the solution you'd like**
When the file browser has multiple Competitions to select from.. When Importing data, what indicates which competition the data will be imported into?  

During the import, differentiating the images of the competition would be helpful... Also, with 3 or more, the selecting item would be easy to pick up (other 2 items are in a different state).... But with 2 selections.. How do you make it clear that an item is selected...   note- I'm seeing this on a lot of UI's right now. when you have a toggle switch an you don't know what is the active state:

ie".       erase everything on disk.   xxxxoooo.   <-- which state is correct

**Comment by RobertBouillon** [comment]
Importing a competition always creates a new competition file.

This is by-design, as importing data into an existing competition creates a number of error scenarios, which would have to be covered by additional development and testing.

Importing into an existing file is a feature that I'd like to add once I've added competition validation, which should catch any errors caused by the import without any additional effort.

**Comment by gregw94542** [comment]
So for clarification.. 
 Creating a new competition = import <this will create a competition file>
 
not
 1) Create competition
 2) import data into the competition

**Comment by RobertBouillon** [comment]
Correct

**Comment by RobertBouillon** [comment]
Will resolve this in #135
